d1=dict(zip(input1,2("keys1: ").split(','),input("values1: ").split(',')))
d2=dict(zip(input("keys2: ").split(','),input("values2: ").split(',')))
d3=sorted(d1)
print("sorted dictionary: ",d3)
d4=d3.copy()
print("copy of sorted dictionary: ",d4)
k1=sorted(d1.keys())
print("sorted keys: ",k1)
v1=sorted(d1.values())
print("sorted values: ",v1)
d1.update(d2)
print("sorted dictionary after updation: ",sorted(d1.items()))
