num1=input("str1= ")
num2=input("str2 = ")
print("Is",num1,"equal to",num2,"=",(num1==num2))
print("Is",num1,"not equal to",num2,"=",(num1!=num2))
print("Is",num1,"greater than",num2,"=",(num1>num2))
print("Is",num1,"less than",num2,"=",(num1<num2))
print("Is",num1,"greater than or equal to",num2,"=",(num1>=num2))
print("Is",num1,"less than or equal to",num2,"=",(num1<=num2))
